baseURL: "https://yanrui06.github.io/"
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: Zephyr的技术博客
  description: "技术分享与学习笔记"
  keywords: [Blog, Portfolio, Development]
  author: Zephyr
  DateFormat: "2006-01-02"
  defaultTheme: auto
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  analytics:
    google:
      disable: true

  profileMode:
    enabled: false
    title: "Zephyr的技术博客"
    subtitle: "分享技术，记录成长"
    imageUrl: "https://github.com/YanRui06.png"
    imageWidth: 120
    imageHeight: 120
    buttons:
      - name: 首页
        url: /
      - name: 文章
        url: posts
      - name: 归档
        url: archives
      - name: 项目
        url: projects
      - name: 关于
        url: about

  socialIcons:
    - name: github
      url: "https://github.com/YanRui06"

  mainSections: ["posts"]

  # 启用归档页面
  enableArchive: true

menu:
  main:
    - identifier: home
      name: 首页
      url: /
      weight: 5
    - identifier: posts
      name: 文章
      url: /posts/
      weight: 10
    - identifier: archives
      name: 归档
      url: /archives/
      weight: 15
    - identifier: projects
      name: 项目
      url: /projects/
      weight: 20
    - identifier: about
      name: 关于
      url: /about/
      weight: 30

pagination:
  pagerSize: 5